modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/LegoMaster3650/ItemUpgrader/issues"

[[mods]]
modId="itemupgrader_content"
version="${file.jarVersion}"
displayName="Item Upgrader"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/itemupgrader"
logoFile="itemupgrader_content.png"
credits="UmbralSurvivor (Pumpkin Head Upgrade)"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
Main Item Upgrader mod, containing the main line of upgrades and some slightly more invasive features
'''

[[dependencies.itemupgrader_content]]
	modId="forge"
	mandatory=true
	versionRange="[43.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemupgrader_content]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemupgrader_content]]
	modId="itemupgrader"
	mandatory=true
	versionRange="[1.0.2,)"
	ordering="NONE"
	side="BOTH"

[modproperties.itemupgrader_content]
	catalogueItemIcon="itemupgrader_content_small.png"