modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="itemupgrader"
version="${file.jarVersion}"
displayName="Item Upgrader"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="itemupgrader.png"
#credits="Joe Mama"
authors="LegoMaster3650"
description='''
Yeah this is a mod it does stuff and things
'''

[[dependencies.itemupgrader]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemupgrader]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="BOTH"

[modproperties.itemupgrader]
	catalogueItemIcon="minecraft:smithing_table"